### ISSUE TITLE
rocket::router - GET /cors/<status> and GET /<file..> collide!

### ISSUE THREAD

**Issue by Boscop** [lawliet89/rocket_cors#29]
When using this crate, I get this error, how to solve this?
```
rocket::router - GET /cors/<status> and GET /<file..> collide!
```
I need to have the `GET /<file..>` route because I'm serving a PWA with all non-api routes corresponding to files on disk.
Why does the cors crate need to create its own route?

**Comment by lawliet89** [comment]
I am assuming that you are using the `Fairing` method to provide CORS.

The Fairing API is fairly limiting in what Fairings can do in its [lifecycle](https://rocket.rs/guide/fairings/). Ideally, we want to validate the CORS request during `on_request`, and if the validation fails, we want to stop the route from even executing to

1) prevent side effects
1) prevent resource usage from unnecessary computation

The only way for me to do this is to hijack the request and route it to our own injected route. 

For your case, there are a couple of things to do:

1) Change your route to have a lower [rank](https://rocket.rs/guide/requests/) (and thus higher precedence). This might work. Currently, I have the injected [route](https://github.com/lawliet89/rocket_cors/blob/c99083af5d22fad25dbfd88bdf031e7745ea218a/src/fairing.rs#L57) have the default rank of `-1`.

For example:

```rust
#[get("/<file..>", rank = -10)]
fn files(file: PathBuf) -> Option<NamedFile> {
    NamedFile::open(Path::new("static/").join(file)).ok()
}
```

1) I will add a configuration option so that the rank of the injected route can be changed.

Please let me know if my suggested solution works.

**Comment by Boscop** [comment]
Why a negative rank? Aren't ranks with higher numbers prioritized less? (rank 1 highest, then rank 2 etc.)
It seems to work with rank 2, but I have another problem:
Even though my api login request returns a cookie like `Set-Cookie:user_id=g8J9djx%2FxGyrVflnYlzDgaDcEGQiAD4KTfnzC57J; SameSite=Strict; Path=/` it's not set in Chrome! Any idea why? On the top left when I click on the SSL cert to the left of the URL, it shows `Cookies: 0 in use` whereas the same endpoint works in my normal non-cors usecase. (The main web app is not on a subdomain, so it's not CORS, and it works with cookies. But the 2nd web app which uses the same api is on a subdomain so it's CORS.)
Any idea how I can make the browser set the cookie like it's supposed to?

**Comment by lawliet89** [comment]
As far as I understand, the ranks are processed in increasing order. That is a lower rank number will have higher precedence.

For cookies, I think you need to turn on `allow_credentials`: https://lawliet89.github.io/rocket_cors/rocket_cors/struct.Cors.html#structfield.allow_credentials

**Comment by Boscop** [comment]
I did:
```rust
	let (allowed_origins, _failed_origins) = AllowedOrigins::some(&["https://subdomain.mydomain.com"]);
	let cors = rocket_cors::Cors {
		allowed_origins,
		allowed_methods: vec![Method::Get, Method::Post].into_iter().map(From::from).collect(),
		allowed_headers: AllowedHeaders::all(),
		allow_credentials: true,
		..Default::default()
	};
```
Btw, doesn't `allow_credentials` only affect request headers (not response headers)? So if a request sends a cookie, whether it will be accepted by the server?

I see the set-cookie header in the response in chrome dev tools, but chrome is not setting the cookie for some reason! (And I didn't disallow thirdparty cookies in the settings either.) So what could be the reason why it's not setting the cookies?

**Comment by lawliet89** [comment]
Can you send me examples of the preflight request and responses?

I am putting a shot in the dark that you need to add `Set-Cookie` to `allowed_headers`: https://lawliet89.github.io/rocket_cors/rocket_cors/struct.Cors.html#structfield.allowed_headers

Not entirely sure.

**Comment by Boscop** [comment]
Preflight login request and response headers:
```
Request URL:https://mydomain.com/api/v1/login
Request Method:OPTIONS
Status Code:204 No Content
Remote Address:144.76.103.202:443
Referrer Policy:no-referrer-when-downgrade

Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:content-type
Access-Control-Allow-Methods:POST
Access-Control-Allow-Origin:https://m.mydomain.com
Connection:keep-alive
Content-Length:0
Content-Type:text/html; charset=utf-8
Date:Fri, 05 Jan 2018 02:03:32 GMT
Server:nginx/1.13.1
Strict-Transport-Security:max-age=63072000; includeSubdomains
X-Content-Type-Options:nosniff
X-Frame-Options:DENY

Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9,de;q=0.8
Access-Control-Request-Headers:content-type
Access-Control-Request-Method:POST
Cache-Control:no-cache
Connection:keep-alive
Host:mydomain.com
Origin:https://m.mydomain.com
Pragma:no-cache
User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
```

Actual login request / response headers:
```
Request URL:https://mydomain.com/api/v1/login
Request Method:POST
Status Code:200 OK
Remote Address:144.76.103.202:443
Referrer Policy:no-referrer-when-downgrade

Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:https://m.mydomain.com
Connection:keep-alive
Content-Length:97
Content-Type:application/json
Date:Fri, 05 Jan 2018 02:03:32 GMT
Server:nginx/1.13.1
Set-Cookie:user_id=g8J9djx%2FxGyrVflnYlzDgaDcEGQiAD4KTfnzC57J; SameSite=Strict; Path=/
Strict-Transport-Security:max-age=63072000; includeSubdomains
X-Content-Type-Options:nosniff
X-Frame-Options:DENY

Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9,de;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Content-Length:40
Content-Type:application/json
Host:mydomain.com
Origin:https://m.mydomain.com
Pragma:no-cache
Referer:https://m.mydomain.com/
User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
```

As you can see, it returned the Set-Cookie header from the login request, as it should, but chrome isn't setting the cookie for some reason.
And I have `allowed_headers: AllowedHeaders::all()`..

I'd really appreciate if you could help me figure out how to make this work because I have an urgent deadline..

**Comment by lawliet89** [comment]
In your `Set-Cookie` header, maybe the  [`SameSite=Strict;`](https://www.owasp.org/index.php/SameSite) is the one causing the issue.

**Comment by lawliet89** [comment]
[This](http://alexcrichton.com/cookie-rs/cookie/struct.CookieBuilder.html#method.same_site)?

**Comment by Boscop** [comment]
`If the SameSite attribute is "Lax", the cookie is only sent in cross-site requests with "safe" HTTP methods, i.e, GET, HEAD, OPTIONS, TRACE.`
But all our API handlers use `POST`, how to enable it for `POST`, too?

**Comment by Boscop** [comment]
https://security.stackexchange.com/a/168369
> When you don't set the SameSite attribute, the cookie is always sent.

So how can I not set it? :)

**Comment by lawliet89** [comment]
Seems like the library does not support. [This PR](https://github.com/alexcrichton/cookie-rs/pull/91) would allow you to do so.

You might have to fork the library, merge in the patch manually, and then point your dependencies to your forked library.

I would love to help, but this is beyond the scope of this library. So I won't be able to respond further to anything that is outside the scope due to a lack of time.

Good luck.
