### ISSUE TITLE
CORS gives an error when booting with the default settings and accessing with axios.

### ISSUE THREAD

**Issue by satodaiki** [lawliet89/rocket_cors#86]
Hello.

When I start it with a simple code like the following and access the request endpoint with axios from the front end (Vue) that is started separately, an error occurs in CORS.

```rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;

extern crate rocket_cors;

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

fn main() {
    let cors = rocket_cors::CorsOptions::default().to_cors();
    rocket::ignite()
        .mount("/", routes![index])
        .manage(cors)
        .launch();
}
```

If you access it directly from the browser, the response will be returned firmly.

<img width="1440" alt="スクリーンショット 2021-02-21 16 13 44" src="https://user-images.githubusercontent.com/28031209/108618267-100e7f00-7460-11eb-903d-cc9770833bdf.png">

The code for axios is below:

```typescript
const test = await axios.get('http://localhost:8000/');
```

The errors displayed on the console are:

<img width="1424" alt="スクリーンショット 2021-02-21 16 18 49" src="https://user-images.githubusercontent.com/28031209/108618329-81e6c880-7460-11eb-9fa6-078f870b09f0.png">

Do you know why?

## Information such as version

- Rust version

nightly-x86_64-apple-darwin (default)
rustc 1.51.0-nightly (c5eae5629 2021-01-11)

- Cargo.toml

```
[dependencies]
rocket = "0.4.7"
rocket_cors = "0.5.2"
```

**Comment by torkleyy** [comment]
You need to `.attach` the fairing, not manage it (the latter ist just for state management). See [the example](https://github.com/lawliet89/rocket_cors/blob/v0.5.2/examples/fairing.rs#L29).

**Comment by satodaiki** [comment]
Thank you very much!
